version: '2'
services:
    gipstergtwy-app:
        image: gipstergtwy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gipstergtwy-postgresql:5432/gipsterGtwy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gipstergtwy-postgresql:
        extends:
            file: postgresql.yml
            service: gipstergtwy-postgresql
